# Dependencies
markdown:         kramdown
highlighter:      rouge

title: Victor Huang
tagline: 'interesting things ahead'
email: victorhuangwq@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  On the lookout for new experiences. 
  Product & Software. CS @ Carnegie Mellon
baseurl: '/' # the subpath of your site, e.g. /blog
url: http://victorhuangwq.github.io

author:
  github: victorhuangwq
  name: 'Victor Huang'
  url: https://www.linkedin.com/in/victorhuangwq/

paginate: 10

# Build settings
remote_theme: fongandrew/hydeout

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from

sidebar_home_link:  true

google_analytics: UA-187642998-1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
