# Dependencies
markdown:         kramdown
highlighter:      rouge

title: Victor Huang
tagline: 'Product & Software'
email: victorhuangwq@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Product & Software.
baseurl: '/' # the subpath of your site, e.g. /blog
url: "http://victorhuangwq.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author:
  github: victorhuangwq
  name: 'Victor Huang'
  url: 'https://www.linkedin.com/in/victorhuangwq/'


paginate: 5

# Build settings
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
